<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
    	background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        color: #FFFFFF;
        width:  100%;
        height: 100%;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        
        height: 100%;
    }
</style>

<!-- background-image: url(http://framework.zend.com/images/bkg_header.jpg); -->

<div id="welcome">
    <h1>Welcome to tophstar.com!</h1>

 <?php echo $value;?>
    
    <div id="more-information">
    </div>
</div>