<style>
.header-navigation{
padding:1em;
}

#header{
height: 6em; 
/*background-image: url('_zf/images/star-shoot.png');
background-repeat:no-repeat;
background-position:left;
background-size: 25em 2em;
*/
}
</style>


<!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Tophstar</title>
      <?php //echo $this->headLink()->appendStylesheet('/css/global.css') ?>
      
      	<script>window.jQuery 	 || document.write('<script src="_zf/js/libs/jquery-1.10.2.min.js"><\/script>')</script>
      	<script>window.jQuery.ui || document.write('<script src="_zf/js/libs/jquery-ui/jquery-ui-1.10.3.min.js"><\/script>')</script>
      	
    </head>
    <body>
    
    
    
	<div id="header">
		<div class="color-block-black" style="position:absolute; z-index:-99; top:0; left:0; width:100%;height:100%;background-color:black"></div>
        <div class="header-navigation" style="float: left">
            <a href="<?php echo $this->url(
                array('controller'=>'index'),
                'default',
                true) ?>">Home</a>
        </div>
        <div class="header-navigation" style="float: left">
            <a href="<?php echo $this->url(
                array('controller'=>'Coursebuddy'),
                'default',
                true) ?>">Social Solution Stack</a>
        </div>
        <div class="header-navigation" style="float: left">
            <a href="http://www.tophstar.com/wordpress">Blog</a>
        </div>
    </div>
     
    <?php echo $this->layout()->content ?>
     
     <script>
		$(document).ready(function(){
			var headerTiles = '';
			
			for(var i = 0; i < 40; i++){
				if(i%2 == 0){
					headerTiles = headerTiles + '<div '
					headerTiles = headerTiles + 'id="color-block'+i+'"';
					headerTiles = headerTiles + ' class="color-block" style="position:absolute; z-index:-98; top:0; left:';
					headerTiles = headerTiles + i/2*5 + '%; width:5%;height:3em;background-color:D9E9FF"></div>';
				}else{
					headerTiles = headerTiles + '<div '
					headerTiles = headerTiles + 'id="color-block'+i+'"';
					headerTiles = headerTiles + 'class="color-block" style="position:absolute; z-index:-98; top:3em; left:'
					headerTiles = headerTiles + (i-1)/2*5 + '%; width:5%;height:3em;background-color:C0D890"></div>';
				}
			}

			$('#header').append(headerTiles);
			$('#color-block38').html('<img id="color-block38" style="width:100%; height:3em;" src="_zf/images/edge_tree_day.jpg"/></img>');
			tilesWave();
		});

		function tilesWave(){
			var refresh;
			var rate = 80000;
			var waveInterval;

			waveAnimation();

			window.clearInterval(refresh);
			refresh=window.setInterval(
				function(){
					waveAnimation(waveInterval);
				}
			,rate);
		}

		function waveAnimation(waveInterval){
			var waveRate = 200;
			var i=0;
			window.clearInterval(waveInterval);
			waveInterval = window.setInterval(
				function()
				{
					if(i<40)
					{
						if(i%2 == 0)
						{
							$('#color-block'+i).effect('highlight');
						}
					}
					else if(i==40)
					{
						$('.color-block:not(#color-block38)').fadeOut();
						$('#color-block38').html('<img id="color-block38" style="width:100%; height:3em;" src="_zf/images/edge_tree_night.jpg"/></img>');
						$('#color-block38').fadeIn();
					}
					else if(i==100)
					{
						//$('#color-block38').fadeOut();
						$('#color-block38').html('<img id="color-block38" style="width:100%; height:3em;" src="_zf/images/edge_tree_day.jpg"/></img>');
						$('.color-block').fadeIn();						

						window.clearInterval(waveInterval);
					}
					i++;
				}
			,waveRate);
		}
     </script>
     
    </body>
    </html>