<style>
    div#page
    {
    	background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        color: #FFFFFF;
        width:  100%;
        height: 100%;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

</style>


<div id="page">
<br/>
1. SELECT A COURSE
<br/>
2. SELECT AN ASSIGNMENT
<br/>
3. SELECT A PROBLEM
<br/>
4. VIEW QUESTION, ANSWER INPUT
<br/>
5. VIEW CONNECTED COURSE BUDDY (INPUT FROM OTHER STUDENTS)
	<br/>a.Vote On Answers
	<br/>b.Filter by learning style
<br/>
</div>